- name: Documentatie voor Kubernetes met Azure Arc
  href: index.yml
- name: Overzicht
  items:
    - name: Over Kubernetes met Azure Arc
      href: overview.md
- name: Instructiegidsen
  items:
    - name: Verbinding maken met Azure Arc
      items:
        - name: Cluster verbinden
          href: connect-cluster.md
        - name: Onboarding van een service-principal
          href: create-onboarding-service-principal.md
    - name: Beheren
      items:
        - name: Configuraties implementeren met GitOps
          href: use-gitops-connected-cluster.md
        - name: Helm-grafieken implementeren met GitOps
          href: use-gitops-with-helm.md
        - name: GitOps afdwingen met Azure Policy
          href: use-azure-policy.md
        - name: Bewaken met Azure Monitor voor containers
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Toegangsbeheer beleid met Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: IoT-workloads implementeren
          href: deploy-azure-iot-edge-workloads.md
    - name: Problemen oplossen
      href: Troubleshooting.md
- name: Naslaginformatie
  items:
    - name: Ingebouwde modules voor Azure Policy
      displayName: 'samples, policies, definitions'
      href: policy-reference.md